apiVersion: apps/v1
kind: Deployment
metadata:
  name: number-game-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: number-game
  template:
    metadata:
      labels:
        app: number-game
    spec:
      containers:
      - name: number-game
        image: mukeshr29/number-game:latest
        ports:
        - containerPort: 3000

